// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MadcatPackage.proto

package com.mcrazy.database.protoc;

public final class MadcatPackageProtoc {
  private MadcatPackageProtoc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code MQTTServer.PackageType}
   */
  public enum PackageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>presence = 0;</code>
     */
    presence(0),
    /**
     * <code>message = 1;</code>
     */
    message(1),
    /**
     * <code>iq = 2;</code>
     */
    iq(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>presence = 0;</code>
     */
    public static final int presence_VALUE = 0;
    /**
     * <code>message = 1;</code>
     */
    public static final int message_VALUE = 1;
    /**
     * <code>iq = 2;</code>
     */
    public static final int iq_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PackageType valueOf(int value) {
      return forNumber(value);
    }

    public static PackageType forNumber(int value) {
      switch (value) {
        case 0: return presence;
        case 1: return message;
        case 2: return iq;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PackageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PackageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PackageType>() {
            public PackageType findValueByNumber(int number) {
              return PackageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.mcrazy.database.protoc.MadcatPackageProtoc.getDescriptor().getEnumTypes().get(0);
    }

    private static final PackageType[] VALUES = values();

    public static PackageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PackageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MQTTServer.PackageType)
  }

  public interface MadcatPackageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MQTTServer.MadcatPackage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.MQTTServer.PackageType packtype = 1;</code>
     */
    int getPacktypeValue();
    /**
     * <code>.MQTTServer.PackageType packtype = 1;</code>
     */
    com.mcrazy.database.protoc.MadcatPackageProtoc.PackageType getPacktype();

    /**
     * <code>string udid = 2;</code>
     */
    java.lang.String getUdid();
    /**
     * <code>string udid = 2;</code>
     */
    com.google.protobuf.ByteString
        getUdidBytes();

    /**
     * <code>string model = 3;</code>
     */
    java.lang.String getModel();
    /**
     * <code>string model = 3;</code>
     */
    com.google.protobuf.ByteString
        getModelBytes();

    /**
     * <code>sint64 timestamp = 4;</code>
     */
    long getTimestamp();

    /**
     * <code>string devtype = 5;</code>
     */
    java.lang.String getDevtype();
    /**
     * <code>string devtype = 5;</code>
     */
    com.google.protobuf.ByteString
        getDevtypeBytes();
  }
  /**
   * Protobuf type {@code MQTTServer.MadcatPackage}
   */
  public  static final class MadcatPackage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MQTTServer.MadcatPackage)
      MadcatPackageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MadcatPackage.newBuilder() to construct.
    private MadcatPackage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MadcatPackage() {
      packtype_ = 0;
      udid_ = "";
      model_ = "";
      timestamp_ = 0L;
      devtype_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MadcatPackage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              packtype_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              udid_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              model_ = s;
              break;
            }
            case 32: {

              timestamp_ = input.readSInt64();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              devtype_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mcrazy.database.protoc.MadcatPackageProtoc.internal_static_MQTTServer_MadcatPackage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mcrazy.database.protoc.MadcatPackageProtoc.internal_static_MQTTServer_MadcatPackage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage.class, com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage.Builder.class);
    }

    public static final int PACKTYPE_FIELD_NUMBER = 1;
    private int packtype_;
    /**
     * <code>.MQTTServer.PackageType packtype = 1;</code>
     */
    public int getPacktypeValue() {
      return packtype_;
    }
    /**
     * <code>.MQTTServer.PackageType packtype = 1;</code>
     */
    public com.mcrazy.database.protoc.MadcatPackageProtoc.PackageType getPacktype() {
      com.mcrazy.database.protoc.MadcatPackageProtoc.PackageType result = com.mcrazy.database.protoc.MadcatPackageProtoc.PackageType.valueOf(packtype_);
      return result == null ? com.mcrazy.database.protoc.MadcatPackageProtoc.PackageType.UNRECOGNIZED : result;
    }

    public static final int UDID_FIELD_NUMBER = 2;
    private volatile java.lang.Object udid_;
    /**
     * <code>string udid = 2;</code>
     */
    public java.lang.String getUdid() {
      java.lang.Object ref = udid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        udid_ = s;
        return s;
      }
    }
    /**
     * <code>string udid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUdidBytes() {
      java.lang.Object ref = udid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        udid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MODEL_FIELD_NUMBER = 3;
    private volatile java.lang.Object model_;
    /**
     * <code>string model = 3;</code>
     */
    public java.lang.String getModel() {
      java.lang.Object ref = model_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        model_ = s;
        return s;
      }
    }
    /**
     * <code>string model = 3;</code>
     */
    public com.google.protobuf.ByteString
        getModelBytes() {
      java.lang.Object ref = model_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    /**
     * <code>sint64 timestamp = 4;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int DEVTYPE_FIELD_NUMBER = 5;
    private volatile java.lang.Object devtype_;
    /**
     * <code>string devtype = 5;</code>
     */
    public java.lang.String getDevtype() {
      java.lang.Object ref = devtype_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        devtype_ = s;
        return s;
      }
    }
    /**
     * <code>string devtype = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDevtypeBytes() {
      java.lang.Object ref = devtype_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        devtype_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (packtype_ != com.mcrazy.database.protoc.MadcatPackageProtoc.PackageType.presence.getNumber()) {
        output.writeEnum(1, packtype_);
      }
      if (!getUdidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, udid_);
      }
      if (!getModelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, model_);
      }
      if (timestamp_ != 0L) {
        output.writeSInt64(4, timestamp_);
      }
      if (!getDevtypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, devtype_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (packtype_ != com.mcrazy.database.protoc.MadcatPackageProtoc.PackageType.presence.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, packtype_);
      }
      if (!getUdidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, udid_);
      }
      if (!getModelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, model_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(4, timestamp_);
      }
      if (!getDevtypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, devtype_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage)) {
        return super.equals(obj);
      }
      com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage other = (com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage) obj;

      boolean result = true;
      result = result && packtype_ == other.packtype_;
      result = result && getUdid()
          .equals(other.getUdid());
      result = result && getModel()
          .equals(other.getModel());
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && getDevtype()
          .equals(other.getDevtype());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PACKTYPE_FIELD_NUMBER;
      hash = (53 * hash) + packtype_;
      hash = (37 * hash) + UDID_FIELD_NUMBER;
      hash = (53 * hash) + getUdid().hashCode();
      hash = (37 * hash) + MODEL_FIELD_NUMBER;
      hash = (53 * hash) + getModel().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + DEVTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getDevtype().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MQTTServer.MadcatPackage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MQTTServer.MadcatPackage)
        com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mcrazy.database.protoc.MadcatPackageProtoc.internal_static_MQTTServer_MadcatPackage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mcrazy.database.protoc.MadcatPackageProtoc.internal_static_MQTTServer_MadcatPackage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage.class, com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage.Builder.class);
      }

      // Construct using com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        packtype_ = 0;

        udid_ = "";

        model_ = "";

        timestamp_ = 0L;

        devtype_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mcrazy.database.protoc.MadcatPackageProtoc.internal_static_MQTTServer_MadcatPackage_descriptor;
      }

      public com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage getDefaultInstanceForType() {
        return com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage.getDefaultInstance();
      }

      public com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage build() {
        com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage buildPartial() {
        com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage result = new com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage(this);
        result.packtype_ = packtype_;
        result.udid_ = udid_;
        result.model_ = model_;
        result.timestamp_ = timestamp_;
        result.devtype_ = devtype_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage) {
          return mergeFrom((com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage other) {
        if (other == com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage.getDefaultInstance()) return this;
        if (other.packtype_ != 0) {
          setPacktypeValue(other.getPacktypeValue());
        }
        if (!other.getUdid().isEmpty()) {
          udid_ = other.udid_;
          onChanged();
        }
        if (!other.getModel().isEmpty()) {
          model_ = other.model_;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getDevtype().isEmpty()) {
          devtype_ = other.devtype_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int packtype_ = 0;
      /**
       * <code>.MQTTServer.PackageType packtype = 1;</code>
       */
      public int getPacktypeValue() {
        return packtype_;
      }
      /**
       * <code>.MQTTServer.PackageType packtype = 1;</code>
       */
      public Builder setPacktypeValue(int value) {
        packtype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.MQTTServer.PackageType packtype = 1;</code>
       */
      public com.mcrazy.database.protoc.MadcatPackageProtoc.PackageType getPacktype() {
        com.mcrazy.database.protoc.MadcatPackageProtoc.PackageType result = com.mcrazy.database.protoc.MadcatPackageProtoc.PackageType.valueOf(packtype_);
        return result == null ? com.mcrazy.database.protoc.MadcatPackageProtoc.PackageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.MQTTServer.PackageType packtype = 1;</code>
       */
      public Builder setPacktype(com.mcrazy.database.protoc.MadcatPackageProtoc.PackageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        packtype_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MQTTServer.PackageType packtype = 1;</code>
       */
      public Builder clearPacktype() {
        
        packtype_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object udid_ = "";
      /**
       * <code>string udid = 2;</code>
       */
      public java.lang.String getUdid() {
        java.lang.Object ref = udid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          udid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string udid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUdidBytes() {
        java.lang.Object ref = udid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          udid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string udid = 2;</code>
       */
      public Builder setUdid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        udid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string udid = 2;</code>
       */
      public Builder clearUdid() {
        
        udid_ = getDefaultInstance().getUdid();
        onChanged();
        return this;
      }
      /**
       * <code>string udid = 2;</code>
       */
      public Builder setUdidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        udid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object model_ = "";
      /**
       * <code>string model = 3;</code>
       */
      public java.lang.String getModel() {
        java.lang.Object ref = model_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          model_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string model = 3;</code>
       */
      public com.google.protobuf.ByteString
          getModelBytes() {
        java.lang.Object ref = model_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          model_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string model = 3;</code>
       */
      public Builder setModel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        model_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string model = 3;</code>
       */
      public Builder clearModel() {
        
        model_ = getDefaultInstance().getModel();
        onChanged();
        return this;
      }
      /**
       * <code>string model = 3;</code>
       */
      public Builder setModelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        model_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>sint64 timestamp = 4;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>sint64 timestamp = 4;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint64 timestamp = 4;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object devtype_ = "";
      /**
       * <code>string devtype = 5;</code>
       */
      public java.lang.String getDevtype() {
        java.lang.Object ref = devtype_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          devtype_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string devtype = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDevtypeBytes() {
        java.lang.Object ref = devtype_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          devtype_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string devtype = 5;</code>
       */
      public Builder setDevtype(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        devtype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string devtype = 5;</code>
       */
      public Builder clearDevtype() {
        
        devtype_ = getDefaultInstance().getDevtype();
        onChanged();
        return this;
      }
      /**
       * <code>string devtype = 5;</code>
       */
      public Builder setDevtypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        devtype_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MQTTServer.MadcatPackage)
    }

    // @@protoc_insertion_point(class_scope:MQTTServer.MadcatPackage)
    private static final com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage();
    }

    public static com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MadcatPackage>
        PARSER = new com.google.protobuf.AbstractParser<MadcatPackage>() {
      public MadcatPackage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MadcatPackage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MadcatPackage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MadcatPackage> getParserForType() {
      return PARSER;
    }

    public com.mcrazy.database.protoc.MadcatPackageProtoc.MadcatPackage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MQTTServer_MadcatPackage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MQTTServer_MadcatPackage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023MadcatPackage.proto\022\nMQTTServer\"{\n\rMad" +
      "catPackage\022)\n\010packtype\030\001 \001(\0162\027.MQTTServe" +
      "r.PackageType\022\014\n\004udid\030\002 \001(\t\022\r\n\005model\030\003 \001" +
      "(\t\022\021\n\ttimestamp\030\004 \001(\022\022\017\n\007devtype\030\005 \001(\t*0" +
      "\n\013PackageType\022\014\n\010presence\020\000\022\013\n\007message\020\001" +
      "\022\006\n\002iq\020\002B1\n\032com.mcrazy.database.protocB\023" +
      "MadcatPackageProtocb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MQTTServer_MadcatPackage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MQTTServer_MadcatPackage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MQTTServer_MadcatPackage_descriptor,
        new java.lang.String[] { "Packtype", "Udid", "Model", "Timestamp", "Devtype", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
